### list categories
GET http://localhost:3000/api/category

### list categories with pagination
GET http://localhost:3000/api/category?page=1&limit=10

### get category by id
GET http://localhost:3000/api/category/4

### create category
POST http://localhost:3000/api/category
Content-Type: application/json

{
    "name": "category name",
    "image_link": "image link"
}

### update category
PUT http://localhost:3000/api/category/1
{
    "name": "category name"
}

### delete category
DELETE http://localhost:3000/api/category/4